[versions]
activity = "1.7.0"
androidGradlePlugin = "7.4.2"
kotlin = "1.8.10"

[libraries]
androidGradlePluginz = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
androidxActivityCompose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
kotlinGradlePluginz = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
